### ISSUE TITLE
I got this issue

### ISSUE THREAD

**Issue by root-420** [UltimateHackers/sqlmate#10]
![screenshot from 2018-06-02 15-23-37](https://user-images.githubusercontent.com/36526237/40873164-f9811baa-6678-11e8-9412-1b261dcc9e2b.png)

**Comment by datasoul1991** [comment]
got it, too....

**Comment by Camel-light** [comment]
Me too...

**Comment by s0md3v** [comment]
Here's a potential fix:
```
pip install bs4
pip install html5lib
pip install lxml
```
If it doesn't work, try this:
```
pip install html5lib==0.9999999
```

**Comment by 23071985** [comment]
thankyou
