### ISSUE TITLE
issue installing the requirements.txt 

### ISSUE THREAD

**Issue by newb1885** [UltimateHackers/sqlmate#4]
trying to install this program on osx -- i have both python version 2 and 3 and pip 2 & 3 installed but keep getting errors:

iMac% pip3 install requirements.txt
Collecting requirements.txt
  Could not find a version that satisfies the requirement requirements.txt (from versions: )
No matching distribution found for requirements.txt
iMac% man pip
No manual entry for pip
iMac% pwd
/Users/kimberly/Documents/GitHub/sqlmate
iMac% ls
LICENSE			paths.txt		sqlmate
README.md		requirements.txt	venv
iMac% pip install requirements.txt
Collecting requirements.txt
  Could not find a version that satisfies the requirement requirements.txt (from versions: )
No matching distribution found for requirements.txt
iMac%
not sure how to proceed. many thanks

**Comment by psychomad** [comment]
same problem for me. im using kali.
I  tried to usa pip search and other way... no luck

**Comment by s0md3v** [comment]
[Fixed] Sorry for late response.
