### ISSUE TITLE
NameError: global name 'login' is not defined

### ISSUE THREAD

**Issue by kalinerd** [UltimateHackers/sqlmate#6]
when sqlmate try to bypass thats what i get 

Traceback (most recent call last):
  File "sqlmate", line 367, in <module>
    bypass()
  File "sqlmate", line 271, in bypass
    find(url, i_title, original)
  File "sqlmate", line 226, in find
    brute(username, passwd, menu, option, name, form_number, i_title, original) #Calls the bruteforce function
  File "sqlmate", line 259, in brute
    print '\n\033[1;32m[+]\033[0m ' + login
NameError: global name 'login' is not defined

word of truth "by far that's the best script until now i'm testing"

**Comment by s0md3v** [comment]
[Fixed]
Thanks
