### ISSUE TITLE
Script stops executing

### ISSUE THREAD

**Issue by emilyanncr** [UltimateHackers/sqlmate#9]
Seems like a really awesome tool.  I'm having problems with it completing though.  The script begins to pull links and find admin panels then just stops.  I've ran it several times.

snip
.....
[-] http://www.hr.dmh.go.th/hr/stat/click_paths.asp?hit_id=475
[-] http://www.dmh.go.th/PoliticCrisis/stat/click_paths.asp?hit_id=6508
[-] http://www.dmh.go.th/PoliticCrisis/stat/click_paths.asp?hit_id=520
[-] http://www.dmh.go.th/PoliticCrisis/stat/click_paths.asp?hit_id=5986
[-] http://www.dmh.go.th/PoliticCrisis/stat/click_paths.asp?hit_id=4974
[-] http://www.dmh.go.th/PoliticCrisis/stat/click_paths.asp?hit_id=5011
[-] http://www.dmh.go.th/politiccrisis/stat/click_paths.asp?hit_id=2333

[>] You will also need their admin panels right? Wait a minute..

[>]Let me try to bypass logins. I want to show SQLmap that I am not a noob.

emily@kali:~/sqlmate$ 
....
snip

Thanks

**Comment by s0md3v** [comment]
Its because `sqlmate` failed to bypass admin panels.
